// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_def.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "packet_def.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protobuf_packet_5fdef_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[6];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "packet_def.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020packet_def.proto*\321\003\n\tGameMsgID\022\017\n\013MSG_"
      "UNKNOWN\020\000\022\024\n\020MSG_EVENT_RESULT\020\001\022\027\n\023MSG_E"
      "VENT_TRANSPOND\020\002\022\024\n\020MSG_CLOSE_SOCKET\020\003\022\024"
      "\n\020MSG_STS_NET_INFO\0202\022\026\n\022MSG_STS_HEART_BE"
      "AT\020d\022\021\n\rMSG_REQ_LOGIN\020e\022\021\n\rMSG_ACK_LOGIN"
      "\020f\022\022\n\016MSG_REQ_LOGOUT\020g\022\032\n\026MSG_REQ_CREATE"
      "_ACCOUNT\020j\022\032\n\026MSG_ACK_CREATE_ACCOUNT\020k\022\027"
      "\n\023MSG_REQ_SERVER_LIST\020n\022\027\n\023MSG_ACK_SERVE"
      "R_LIST\020o\022\031\n\025MSG_REQ_CREATE_PLAYER\020x\022\031\n\025M"
      "SG_ACK_CREATE_PLAYER\020y\022\030\n\023MSG_REQ_ENTER_"
      "WORLD\020\202\001\022\030\n\023MSG_ACK_ENTER_WORLD\020\203\001\022\030\n\023MS"
      "G_REQ_MOVE_PLAYER\020\214\001\022\030\n\023MSG_ACK_MOVE_PLA"
      "YER\020\215\001*\200\001\n\010RetError\022\023\n\017RET_ERR_UNKNOWN\020\000"
      "\022\023\n\017RET_ERR_NOERROR\020\001\022\022\n\016RET_ERR_COMMON\020"
      "\n\022\032\n\026RET_ERR_DB_ACCESS_FAIL\020d\022\032\n\026RET_ERR"
      "_DB_WRONG_QUERY\020e*\\\n\020RetCreateAccount\022\026\n"
      "\022RET_CREATE_SUCCESS\020\000\022\032\n\026RET_EXIST_ACCOU"
      "NT_FAIL\020\001\022\024\n\020RET_UNKONWN_FAIL\020\002*n\n\010RetLo"
      "gin\022\022\n\016RET_LOGIN_FAIL\020\000\022\025\n\021RET_LOGIN_SUC"
      "CESS\020\001\022\027\n\023RET_LOGIN_WRONGPASS\020\002\022\036\n\032RET_L"
      "OGIN_NEED_CREATE_USER\020\003*l\n\017RetCreatePlay"
      "er\022\032\n\026RET_CREATE_PLAYER_FAIL\020\000\022\035\n\031RET_CR"
      "EATE_PLAYER_SUCCESS\020\001\022\036\n\032RET_CREATE_PLAY"
      "ER_CONFLICT\020\002*D\n\rRetServerList\022\027\n\023RET_SE"
      "RVERLIST_FAIL\020\000\022\032\n\026RET_SERVERLIST_SUCCES"
      "S\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1011);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "packet_def.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_packet_5fdef_2eproto

const ::google::protobuf::EnumDescriptor* GameMsgID_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[0];
}
bool GameMsgID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 50:
    case 100:
    case 101:
    case 102:
    case 103:
    case 106:
    case 107:
    case 110:
    case 111:
    case 120:
    case 121:
    case 130:
    case 131:
    case 140:
    case 141:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RetError_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[1];
}
bool RetError_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 10:
    case 100:
    case 101:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RetCreateAccount_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[2];
}
bool RetCreateAccount_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RetLogin_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[3];
}
bool RetLogin_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RetCreatePlayer_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[4];
}
bool RetCreatePlayer_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RetServerList_descriptor() {
  protobuf_packet_5fdef_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fdef_2eproto::file_level_enum_descriptors[5];
}
bool RetServerList_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
