// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_def.proto

#ifndef PROTOBUF_packet_5fdef_2eproto__INCLUDED
#define PROTOBUF_packet_5fdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_packet_5fdef_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_packet_5fdef_2eproto

enum GameMsgID {
  MSG_UNKNOWN = 0,
  MSG_EVENT_RESULT = 1,
  MSG_EVENT_TRANSPOND = 2,
  MSG_CLOSE_SOCKET = 3,
  MSG_STS_NET_INFO = 50,
  MSG_STS_HEART_BEAT = 100,
  MSG_REQ_LOGIN = 101,
  MSG_ACK_LOGIN = 102,
  MSG_REQ_LOGOUT = 103,
  MSG_REQ_CREATE_ACCOUNT = 106,
  MSG_ACK_CREATE_ACCOUNT = 107,
  MSG_REQ_SERVER_LIST = 110,
  MSG_ACK_SERVER_LIST = 111,
  MSG_REQ_CREATE_PLAYER = 120,
  MSG_ACK_CREATE_PLAYER = 121,
  MSG_REQ_ENTER_WORLD = 130,
  MSG_ACK_ENTER_WORLD = 131,
  MSG_REQ_MOVE_PLAYER = 140,
  MSG_ACK_MOVE_PLAYER = 141,
  GameMsgID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GameMsgID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GameMsgID_IsValid(int value);
const GameMsgID GameMsgID_MIN = MSG_UNKNOWN;
const GameMsgID GameMsgID_MAX = MSG_ACK_MOVE_PLAYER;
const int GameMsgID_ARRAYSIZE = GameMsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* GameMsgID_descriptor();
inline const ::std::string& GameMsgID_Name(GameMsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    GameMsgID_descriptor(), value);
}
inline bool GameMsgID_Parse(
    const ::std::string& name, GameMsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameMsgID>(
    GameMsgID_descriptor(), name, value);
}
enum RetError {
  RET_ERR_UNKNOWN = 0,
  RET_ERR_NOERROR = 1,
  RET_ERR_COMMON = 10,
  RET_ERR_DB_ACCESS_FAIL = 100,
  RET_ERR_DB_WRONG_QUERY = 101,
  RetError_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RetError_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RetError_IsValid(int value);
const RetError RetError_MIN = RET_ERR_UNKNOWN;
const RetError RetError_MAX = RET_ERR_DB_WRONG_QUERY;
const int RetError_ARRAYSIZE = RetError_MAX + 1;

const ::google::protobuf::EnumDescriptor* RetError_descriptor();
inline const ::std::string& RetError_Name(RetError value) {
  return ::google::protobuf::internal::NameOfEnum(
    RetError_descriptor(), value);
}
inline bool RetError_Parse(
    const ::std::string& name, RetError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetError>(
    RetError_descriptor(), name, value);
}
enum RetCreateAccount {
  RET_CREATE_SUCCESS = 0,
  RET_EXIST_ACCOUNT_FAIL = 1,
  RET_UNKONWN_FAIL = 2,
  RetCreateAccount_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RetCreateAccount_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RetCreateAccount_IsValid(int value);
const RetCreateAccount RetCreateAccount_MIN = RET_CREATE_SUCCESS;
const RetCreateAccount RetCreateAccount_MAX = RET_UNKONWN_FAIL;
const int RetCreateAccount_ARRAYSIZE = RetCreateAccount_MAX + 1;

const ::google::protobuf::EnumDescriptor* RetCreateAccount_descriptor();
inline const ::std::string& RetCreateAccount_Name(RetCreateAccount value) {
  return ::google::protobuf::internal::NameOfEnum(
    RetCreateAccount_descriptor(), value);
}
inline bool RetCreateAccount_Parse(
    const ::std::string& name, RetCreateAccount* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetCreateAccount>(
    RetCreateAccount_descriptor(), name, value);
}
enum RetLogin {
  RET_LOGIN_FAIL = 0,
  RET_LOGIN_SUCCESS = 1,
  RET_LOGIN_WRONGPASS = 2,
  RET_LOGIN_NEED_CREATE_USER = 3,
  RetLogin_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RetLogin_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RetLogin_IsValid(int value);
const RetLogin RetLogin_MIN = RET_LOGIN_FAIL;
const RetLogin RetLogin_MAX = RET_LOGIN_NEED_CREATE_USER;
const int RetLogin_ARRAYSIZE = RetLogin_MAX + 1;

const ::google::protobuf::EnumDescriptor* RetLogin_descriptor();
inline const ::std::string& RetLogin_Name(RetLogin value) {
  return ::google::protobuf::internal::NameOfEnum(
    RetLogin_descriptor(), value);
}
inline bool RetLogin_Parse(
    const ::std::string& name, RetLogin* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetLogin>(
    RetLogin_descriptor(), name, value);
}
enum RetCreatePlayer {
  RET_CREATE_PLAYER_FAIL = 0,
  RET_CREATE_PLAYER_SUCCESS = 1,
  RET_CREATE_PLAYER_CONFLICT = 2,
  RetCreatePlayer_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RetCreatePlayer_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RetCreatePlayer_IsValid(int value);
const RetCreatePlayer RetCreatePlayer_MIN = RET_CREATE_PLAYER_FAIL;
const RetCreatePlayer RetCreatePlayer_MAX = RET_CREATE_PLAYER_CONFLICT;
const int RetCreatePlayer_ARRAYSIZE = RetCreatePlayer_MAX + 1;

const ::google::protobuf::EnumDescriptor* RetCreatePlayer_descriptor();
inline const ::std::string& RetCreatePlayer_Name(RetCreatePlayer value) {
  return ::google::protobuf::internal::NameOfEnum(
    RetCreatePlayer_descriptor(), value);
}
inline bool RetCreatePlayer_Parse(
    const ::std::string& name, RetCreatePlayer* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetCreatePlayer>(
    RetCreatePlayer_descriptor(), name, value);
}
enum RetServerList {
  RET_SERVERLIST_FAIL = 0,
  RET_SERVERLIST_SUCCESS = 1,
  RetServerList_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RetServerList_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RetServerList_IsValid(int value);
const RetServerList RetServerList_MIN = RET_SERVERLIST_FAIL;
const RetServerList RetServerList_MAX = RET_SERVERLIST_SUCCESS;
const int RetServerList_ARRAYSIZE = RetServerList_MAX + 1;

const ::google::protobuf::EnumDescriptor* RetServerList_descriptor();
inline const ::std::string& RetServerList_Name(RetServerList value) {
  return ::google::protobuf::internal::NameOfEnum(
    RetServerList_descriptor(), value);
}
inline bool RetServerList_Parse(
    const ::std::string& name, RetServerList* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RetServerList>(
    RetServerList_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::GameMsgID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameMsgID>() {
  return ::GameMsgID_descriptor();
}
template <> struct is_proto_enum< ::RetError> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RetError>() {
  return ::RetError_descriptor();
}
template <> struct is_proto_enum< ::RetCreateAccount> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RetCreateAccount>() {
  return ::RetCreateAccount_descriptor();
}
template <> struct is_proto_enum< ::RetLogin> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RetLogin>() {
  return ::RetLogin_descriptor();
}
template <> struct is_proto_enum< ::RetCreatePlayer> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RetCreatePlayer>() {
  return ::RetCreatePlayer_descriptor();
}
template <> struct is_proto_enum< ::RetServerList> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RetServerList>() {
  return ::RetServerList_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_packet_5fdef_2eproto__INCLUDED
